var five = 5;
var ten = 10;
console.log("test1 five is equal to 5?");
console.log(five == 5);
console.log("\ntest2 ten is equal to 10?");
console.log(ten == 10);
console.log("\ntest3 five is not equalto 10/");
console.log(five != 10);
console.log("\ntest4 ten is greator than  5?");
console.log(ten > 5);
console.log("\ntest5 five is smaller than 10?");
console.log(five < 10);
console.log("\ntest6 five is greator than 10?");
console.log(five > 10);
console.log("\ntest7 ten is smaller than 5?");
console.log(10 < 5);
console.log("\ntest8 five is equal to 10?");
console.log(five == 10);
console.log("\ntest9 10 is  not equal to 10?");
console.log(ten != 10);
console.log("\n100 is smaller than 50?");
console.log(100 < 50);
